export const $ = id => document.getElementById(id);
export const el = {
  navbar: $('navbar'), navBack: $('navBack'), navSteps: document.querySelectorAll('.step'),
  nsPlayer: $('nsPlayer'), nsAi: $('nsAi'),
  // Single Player Game
  webcamVideo: $('webcamVideo'), overlayCanvas: $('overlayCanvas'),
  camBox: $('camBox'), camPlaceholder: $('camPlaceholder'),
  countdownOverlay: $('countdownOverlay'),
  startCamBtn: $('startCamBtn'), stopCamBtn: $('stopCamBtn'),
  captureBtn: $('captureBtn'),
  playerTag: $('playerTag'), playerTagEmoji: $('playerTagEmoji'), playerTagLabel: $('playerTagLabel'),
  aiIdle: $('aiIdle'), aiShow: $('aiShow'), aiGestureEmoji: $('aiGestureEmoji'),
  aiTag: $('aiTag'), aiTagEmoji: $('aiTagEmoji'), aiTagLabel: $('aiTagLabel'),
  vsResult: $('vsResult'),
  scorePlayer: $('scorePlayer'), scoreDraw: $('scoreDraw'), scoreAi: $('scoreAi'),
  resetScoreBtn: $('resetScoreBtn'),
  spInputSelector: $('spInputSelector'), spBtnUseCam: $('spBtnUseCam'), spBtnUseUpload: $('spBtnUseUpload'),
  gameModeWebcam: $('gameModeWebcam'), gameModeUpload: $('gameModeUpload'),
  // Single Player Upload
  uploadDrop: $('uploadDrop'), uploadDropInner: $('uploadDropInner'),
  fileInput: $('fileInput'), chooseFileBtn: $('chooseFileBtn'),
  uploadResultPanel: $('uploadResultPanel'), previewImg: $('previewImg'),
  annotatedImg: $('annotatedImg'), annotatedWrap: $('annotatedWrap'),
  uploadEmoji: $('uploadEmoji'), uploadGestureLabel: $('uploadGestureLabel'),
  playUploadBtn: $('playUploadBtn'), uploadLoading: $('uploadLoading'),
  // Multiplayer Lobby
  mpPlayerNameInput: $('mpPlayerNameInput'),
  btnRandomName: $('btnRandomName'),
  btnCreateRoom: $('btnCreateRoom'),
  mpRoomCodeInput: $('mpRoomCodeInput'),
  btnJoinRoom: $('btnJoinRoom'),
  lobbySetup: $('lobbySetup'),
  lobbyWaiting: $('lobbyWaiting'),
  roomCodeVal: $('roomCodeVal'),
  btnCopyLink: $('btnCopyLink'),
  slotPlayer1: $('slotPlayer1'),
  slotP1Name: $('slotP1Name'),
  slotPlayer2: $('slotPlayer2'),
  slotP2Name: $('slotP2Name'),
  slotP2Icon: $('slotP2Icon'),
  slotP2Desc: $('slotP2Desc'),
  lobbyStatusMsg: $('lobbyStatusMsg'),
  btnStartMpGame: $('btnStartMpGame'),
  btnBackLobby: $('btnBackLobby'),
  // Multiplayer Game Arena
  mpScoreP1Label: $('mpScoreP1Label'),
  mpScorePlayer: $('mpScorePlayer'),
  mpScoreDraw: $('mpScoreDraw'),
  mpScoreP2Label: $('mpScoreP2Label'),
  mpScoreOpponent: $('mpScoreOpponent'),
  mpLocalLabel: $('mpLocalLabel'),
  mpOpponentLabel: $('mpOpponentLabel'),
  mpCamBox: $('mpCamBox'),
  mpWebcamVideo: $('mpWebcamVideo'),
  mpOverlayCanvas: $('mpOverlayCanvas'),
  mpInputSelector: $('mpInputSelector'),
  mpBtnUseCam: $('mpBtnUseCam'),
  mpBtnUseUpload: $('mpBtnUseUpload'),
  mpUploadZone: $('mpUploadZone'),
  mpFileInput: $('mpFileInput'),
  mpUploadStatus: $('mpUploadStatus'),
  mpCountdownOverlay: $('mpCountdownOverlay'),
  mpCamActions: $('mpCamActions'),
  mpStopCamBtn: $('mpStopCamBtn'),
  mpPlayerTag: $('mpPlayerTag'),
  mpPlayerTagEmoji: $('mpPlayerTagEmoji'),
  mpPlayerTagLabel: $('mpPlayerTagLabel'),
  mpCaptureBtn: $('mpCaptureBtn'),
  mpVsResult: $('mpVsResult'),
  mpOpponentBox: $('mpOpponentBox'),
  mpOpponentIdle: $('mpOpponentIdle'),
  mpOpponentStatusText: $('mpOpponentStatusText'),
  mpOpponentShow: $('mpOpponentShow'),
  mpOpponentEmoji: $('mpOpponentEmoji'),
  mpOpponentTag: $('mpOpponentTag'),
  mpOpponentTagEmoji: $('mpOpponentTagEmoji'),
  mpOpponentTagLabel: $('mpOpponentTagLabel'),
  btnLeaveMpGame: $('btnLeaveMpGame'),
  // Result Page
  resultBadge: $('resultBadge'), resultTitle: $('resultTitle'),
  resPlayerEmoji: $('resPlayerEmoji'), resPlayerGesture: $('resPlayerGesture'),
  resAiEmoji: $('resAiEmoji'), resAiGesture: $('resAiGesture'),
  rsPlayer: $('rsPlayer'), rsDraw: $('rsDraw'), rsAi: $('rsAi'),
  rsPlayerLabel: $('rsPlayerLabel'), rsAiLabel: $('rsAiLabel'),
  particleCanvas: $('particleCanvas'),
  toast: $('toast'),
};
